### ISSUE TITLE
Please create a new release

### ISSUE THREAD

**Issue by yongyan-gh** [clj-holmes/clj-watson-action#3]
Can you pls create a new release with the `--output-file` parameter?

Thanks!

**Comment by mthbernardes** [comment]
https://github.com/clj-holmes/clj-watson-action/releases/tag/main
This release contains the output-file parameter.

**Comment by yongyan-gh** [comment]
Thanks! Can you also review the clj-watson starter workflow PR?

https://github.com/actions/starter-workflows/pull/1460
